### ISSUE TITLE
Gitcher doesn't work if there is space in path

### ISSUE THREAD

**Issue by andgein** [bglezseoane/gitcher#2]
I.e., https://github.com/GlezSeoane/gitcher/blob/master/gitcher/model_layer.py#L177

If there is a space in a path, gitcher (and non-interactive gitcher -s) doesn't work:

```
sh: 1: cd: can't cd to /home/andgein/Work/2019/08.
sh: 1: cd: can't cd to /home/andgein/Work/2019/08.
sh: 1: cd: can't cd to /home/andgein/Work/2019/08.
sh: 1: cd: can't cd to /home/andgein/Work/2019/08.
[OK] Switched to Home profile.
```

**Comment by bglezseoane** [comment]
I’ll revise it as soon as possible. Thank you for the input!

**Comment by GlezSeoane** [comment]
The new 2.1 release solves this bug.

**Comment by bglezseoane** [comment]
The new 2.1 version solves this bug.
