### ISSUE TITLE
Correct abuse with the acronym "GPG" where "PGP" corresponds

### ISSUE THREAD

**Issue by bglezseoane** [bglezseoane/gitcher#3]
Canonically, *GPG* means GNU Privacy Guard, and it is an independent implementation of the OpenPGP standards, so you can use it for example to encrypted messages with people using other OpenPGP implementations.

*PGP* is a more correct way of naming the formats for keys, encrypted messages and message signatures defined by an OpenPGP standard software.

In Gitcher and its documentation, these terms do not appear correctly reflected. They are mixed and tend to encompass everything under the acronym *GPG*. This must be corrected according to the previously reflected.

**Comment by abkosar** [comment]
Hey! I would like to give this a shot!

**Comment by bglezseoane** [comment]
Of course! Thanks for your interest. Don't hesitate to write to me in case you need anything. You also have my email in my profile. I look forward to your PR!

**Comment by abkosar** [comment]
Sounds good, on it!

**Comment by bglezseoane** [comment]
This issue has been resolved yet, by @abkosar. The commit has been incorporated into the `develop` branch and will be propagated to `master` in a short time.
